#
#	Global configuration for SNAP makefiles
#

GLIB = glib-core
SNAP = snap-core
GLIBADV = glib-adv
SNAPADV = snap-adv
SNAPEXP = snap-exp

# RamCloud
RCSRC = /home/jdellit/git/ramcloud/src
RCOBJ = /home/jdellit/git/ramcloud/obj.master
RCCBN = /home/jdellit/git/ramcloud/logcabin
RCGTST = /home/jdellit/git/ramcloud/gtest/include
RCLIB = /home/jdellit/git/ramcloud/obj.master/libramcloud.a

CGLIB = ../$(GLIB)
CSNAP = ../$(SNAP)

EXGLIB = ../../$(GLIB)
EXSNAP = ../../$(SNAP)
EXGLIBADV = ../../$(GLIBADV)
EXSNAPADV = ../../$(SNAPADV)
EXSNAPEXP = ../../$(SNAPEXP)

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  # CXXFLAGS += -std=c++98 -Wall
  CXXFLAGS += -std=c++0x -Wall
  # CXXFLAGS += -O3 -DNDEBUG
  CXXFLAGS += -DNDEBUG
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  #CXXFLAGS += -g -rdynamic
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS += -lrt -lpcrecpp -lboost_program_options -lprotobuf -lboost_filesystem -lboost_thread -lboost_system -lpthread -lssl -lcrypto -rdynamic -libverbs

else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = g++
  CXXFLAGS += -std=c++98 -Wall
  CXXFLAGS += -O3 -DNDEBUG
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS +=

else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  CC = g++
  CXXFLAGS += -Wall -D__STDC_LIMIT_MACROS
  CXXFLAGS += -O3 -DNDEBUG
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS +=

endif

